command=$SCRIPT_DIR/$BLOCK_NAME
color=#E0E0E0

[song]
command=xprop -name "spotify" _NET_WM_NAME|\cut -d "\"" -f 2|cut -b 11-
label=
interval=1
color=#2ebd59

[volume]
command=/home/vinkel/.config/i3/scripts/volume 2
label= 
interval=1

[date]
command=date '+%H:%M %d/%m'
interval=1
label=
