#!/usr/bin/env zsh

## If alacritty.yml does not exist, raise an alert
[[ ! -f ~/.config/alacritty/alacritty.toml ]] && \
    notify-send "alacritty.toml does not exist" && exit 0

## Fetch background_opacity from alacritty.yml
opacity=$(awk -F'=' '$1 == "opacity " {print $2; exit}' \
    ~/.config/alacritty/alacritty.toml | tr -d '[:space:]')

echo $opacity

## Assign toggle opacity value
case $opacity in
  1)
    toggle_opacity=0.6
    ;;
  *)
    toggle_opacity=1
    ;;
esac

echo $toggle_opacity

## Replace opacity value in alacritty.yml
sed -i -- "s/opacity = $opacity/opacity = $toggle_opacity/" \
    ~/.config/alacritty/alacritty.toml
