#!/usr/bin/env zsh

## Fetch background_opacity from alacritty.yml
opacity=$(awk -F' ' '$1 == "return" {print $2; exit}' \
    ~/.config/wezterm/opacity.lua) 

echo "opacity: $opacity yeah"

## Assign toggle opacity value
case $opacity in
  1)
    toggle_opacity=0.6
    ;;
  *)
    toggle_opacity=1
    ;;
esac

echo $toggle_opacity

## Replace opacity value in alacritty.yml
echo "return $toggle_opacity" > ~/.config/wezterm/opacity.lua
